### ISSUE TITLE
How to run eve-elastic search? 

### ISSUE THREAD

**Issue by satyanani40** [petrjasek/eve-elastic#30]
I am running python eve successfully. then I am imported eve-elastic and then just added data = Elastic,
and then run my server.
Then getting connection refused error.
My eve localhost machine running on 127.0.0.1:8000 port.
Why I am getting connection refused error

**Comment by petrjasek** [comment]
hi, do you run elastic on 127.0.0.1:9200 ?

**Comment by satyanani40** [comment]
I am running python eve in 127.0.0.1:8000. i am just modified my server.py file with 
app = Eve(data=Elastic) and then run my server.py file.
then I am getting connection refused errror.

Is it correct. May I can embedded your code in server.py of python eve, or need to create separate  file ?
I did n't know exactly. please help me.

**Comment by petrjasek** [comment]
you have to add to your schema info about backend:
```
schema = {
    'datasource': {'backend': 'elastic'}
}
```
and then you can use [query dsl](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html) via `source` param
