### ISSUE TITLE
Mention PyMongo dependency

### ISSUE THREAD

**Issue by deeplook** [petrjasek/eve-elastic#39]
Apparently, this package needs PyMongo (https://pypi.python.org/pypi/pymongo), but doesn't say so. And from looking at the code (which imports ```bson.objectid.ObjectID```) it's not evident that another package named bson is not the one needed (https://pypi.python.org/pypi/bson), which causes confusion. The README then should also point out, *why* PyMongo is really needed, since some people (including me) would not expect this if they want to use Eve with Elasticsearch *instead* of MongoDB.

**Comment by petrjasek** [comment]
hey, thanks for pointing it out, I've removed that dependency
