### ISSUE TITLE
How does one go about integrating eve with sqlalchemy with flask?

### ISSUE THREAD

**Issue by rlam3** [petrjasek/eve-elastic#51]
How does one go about integrating eve with sqlalchemy with flask?

**Comment by petrjasek** [comment]
you can create yet another datalayer which will have this logic, we did [something like that](https://github.com/superdesk/superdesk-core/blob/master/superdesk/eve_backend.py#L21) for elastic+mongo. based on resource config some collections are also in elastic and it's used for queries
