### ISSUE TITLE
Is there any support for nested documents?

### ISSUE THREAD

**Issue by ojosdegris** [petrjasek/eve-elastic#66]
And if yes, is there any tests/examples.

thanks!

**Comment by petrjasek** [comment]
not sure exactly what you mean, something like [this](https://github.com/petrjasek/eve-elastic/blob/master/test/test_elastic.py#L25-L32) ?

**Comment by ojosdegris** [comment]
in terms of Eve - yes 
in terms of elastic search,  you need to apply special mapping "nested" ,otherwise document will be flattened out. 
just didnt find any code that would do something like that in this repo.

( ES converts this: `{ "a":{"b":1}}` to `{"a.b":1}` when indexing without nested mapping)

**Comment by petrjasek** [comment]
I see, you could set elastic mapping for a field where you would specify that, via:
```
'field': {
    'type': 'dict',
    'mapping': {'type': 'nested', 'properties': ...}
}
```
but that's about it, no helpers for queries etc
